"""Initial migration

Revision ID: 5fa31c2e5f90
Revises: 
Create Date: 2024-10-15 16:30:47.211649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa31c2e5f90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='分类名'),
    sa.Column('description', sa.String(length=100), nullable=True, comment='描述'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态 1 正常 2 禁用'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='用户类型'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态 1 正常 2 禁用'),
    sa.Column('type', sa.Integer(), nullable=True, comment='类型 1 管理员 2 普通用户'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=20), nullable=True, comment='密码'),
    sa.Column('hashed_password', sa.String(length=100), nullable=True, comment='哈希密码'),
    sa.Column('avatar', sa.String(length=200), nullable=True, comment='头像'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='电话'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('user_type_id', sa.Integer(), nullable=True, comment='用户类型id'),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True, comment='标题'),
    sa.Column('sub_title', sa.String(length=200), nullable=True, comment='副标题'),
    sa.Column('content_json', sa.Text(), nullable=True, comment='内容json'),
    sa.Column('content_html', sa.Text(), nullable=True, comment='内容html'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态 1 发布 2 草稿 3 删除 4 禁用'),
    sa.Column('cover', sa.String(length=200), nullable=True, comment='封面'),
    sa.Column('is_top', sa.Integer(), nullable=True, comment='是否置顶 2 否 1 是'),
    sa.Column('is_recommend', sa.Integer(), nullable=True, comment='是否推荐 2 否 1 是'),
    sa.Column('is_original', sa.Integer(), nullable=True, comment='是否原创 2 否 1 是'),
    sa.Column('is_comment', sa.Integer(), nullable=True, comment='是否评论 2 否 1 是'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类id'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('user_types')
    op.drop_table('categories')
    # ### end Alembic commands ###
