"""change

Revision ID: cd2b214711a0
Revises: e2a6e303e734
Create Date: 2024-10-11 17:10:22.078220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd2b214711a0'
down_revision: Union[str, None] = 'e2a6e303e734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=True))
    op.alter_column('article', 'status',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('article', 'is_top',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('article', 'is_recommend',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('article', 'is_original',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('article', 'is_comment',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'articlelinkcategory', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'articlelinkcategory', 'category', ['category_id'], ['id'])
    op.alter_column('category', 'status',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'usertype', ['user_type_id'], ['id'])
    op.alter_column('usertype', 'status',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('usertype', 'type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usertype', 'type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('usertype', 'status',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type_id')
    op.alter_column('category', 'status',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'articlelinkcategory', type_='foreignkey')
    op.drop_constraint(None, 'articlelinkcategory', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.alter_column('article', 'is_comment',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('article', 'is_original',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('article', 'is_recommend',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('article', 'is_top',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('article', 'status',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
