"""colum change

Revision ID: e63e07b2f286
Revises: ee1a1927fc16
Create Date: 2024-10-17 16:47:23.666578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e63e07b2f286'
down_revision: Union[str, None] = 'ee1a1927fc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'message',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_comment='日志信息',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_comment='日志信息',
               existing_nullable=True)
    # ### end Alembic commands ###
